server {
    listen 80 default_server;
    server_name localhost;

    client_max_body_size 2048m;
    client_body_timeout 600s;
    add_header Strict-Transport-Security "max-age=31536000";

    access_log /var/log/nginx/ada_access.log;
    error_log /var/log/nginx/ada_error.log;

    location / {
        root /home/adadmin/static;
        index index.html;
    }

    location ~ \.(js|css|png|ico|jpg|ttf|woff|srv)$ {
        root /home/adadmin/static;
        gzip on;
        gzip_buffers 4 16k;
        gzip_comp_level 6;
        gzip_vary on;
        gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    }

    location /ada.ADA/ {
        grpc_set_header X-Real-IP $remote_addr;
        grpc_set_header Content-Type application/grpc;
        grpc_pass grpc://127.0.0.1:8800;
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Transfer-Encoding,Custom-Header-1,X-Accept-Content-Transfer-Encoding,X-Accept-Response-Streaming,X-User-Agent,X-Grpc-Web';
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
        if ($request_method = 'POST') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'authorization,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Transfer-Encoding,Custom-Header-1,X-Accept-Content-Transfer-Encoding,X-Accept-Response-Streaming,X-User-Agent,X-Grpc-Web';
            add_header 'Access-Control-Expose-Headers' 'Content-Transfer-Encoding,Grpc-Message,Grpc-Status';
       }
    }

    location ^~/kibana/ {
        proxy_pass http://ada_kibana:5601/;
        rewrite ^/kibana/(.*)$ /$1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "upgrade";

        proxy_intercept_errors on;
    }

    location ^~/download/ {
        alias /home/adadmin/download/;
    }

    location = /lic/trait {
        proxy_pass http://127.0.0.1:8801/lic/trait;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Connection "upgrade";
    }

    location = /webssh/stream {
        proxy_pass http://127.0.0.1:8801/webssh/stream;
        add_header 'Access-Control-Allow-Origin' '*';
        proxy_http_version 1.1;
        proxy_read_timeout 300;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Real-PORT $remote_port;
    }

    error_page 502 503 504 = @kibana_error;
    location @kibana_error {
        default_type text/plain;
        return 503 "ES/Kibana not installed";
    }
}