[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:taskserver]
directory=/home/adadmin/bin
command=/home/adadmin/bin/task_server
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/taskserver.log
stderr_logfile_backups=3
numprocs=1
priority=103
numprocs_start=0
user=adadmin

[program:taskworker]
directory=/home/adadmin/bin
command=/home/adadmin/bin/task_worker
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/taskworker.log
stderr_logfile_backups=3
numprocs=1
priority=104
numprocs_start=0
user=adadmin

[program:apiserver]
directory=/home/adadmin/bin
command=/home/adadmin/bin/apiserver
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/apiserver.log
stderr_logfile_backups=3
numprocs=1
priority=105
numprocs_start=0
user=adadmin

[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true