server.port: 5601
server.host: "127.0.0.1"
server.basePath: "/kibana"
pid.file: /run/kibana/kibana.pid
elasticsearch.hosts: ['http://127.0.0.1:9200']

logging:
  appenders:
    file:
      type: file
      fileName: /var/log/kibana/kibana.log
      layout:
        type: json
  root:
    appenders:
      - default
      - file