http:
  port: "9200"
  host: "0.0.0.0"
path:
  data: /bitnami/elasticsearch/data
discovery:
  type: single-node
xpack:
  security:
    enabled: "false"
    http:
      ssl:
        enabled: "false"
    transport:
      ssl:
        enabled: "false"
