// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0-devel
// 	protoc        v4.25.1
// source: ada_task.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskStateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskUUID string `protobuf:"bytes,1,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"` //任务UUID
}

func (x *GetTaskStateReq) Reset() {
	*x = GetTaskStateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskStateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStateReq) ProtoMessage() {}

func (x *GetTaskStateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStateReq.ProtoReflect.Descriptor instead.
func (*GetTaskStateReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskStateReq) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

type GetTaskStateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskUUID  string `protobuf:"bytes,1,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`   //任务ID
	TaskName  string `protobuf:"bytes,2,opt,name=taskName,proto3" json:"taskName,omitempty"`   //任务名称
	State     string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`         //任务状态 PENDING RECEIVED STARTED RETRY SUCCESS FAILURE
	Error     string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`         //错误日志
	CreatedAt string `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //创建时间
}

func (x *GetTaskStateReply) Reset() {
	*x = GetTaskStateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTaskStateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskStateReply) ProtoMessage() {}

func (x *GetTaskStateReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskStateReply.ProtoReflect.Descriptor instead.
func (*GetTaskStateReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{1}
}

func (x *GetTaskStateReply) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *GetTaskStateReply) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *GetTaskStateReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetTaskStateReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTaskStateReply) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DomainStatusSyncTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DomainStatusSyncTaskReq) Reset() {
	*x = DomainStatusSyncTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainStatusSyncTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainStatusSyncTaskReq) ProtoMessage() {}

func (x *DomainStatusSyncTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainStatusSyncTaskReq.ProtoReflect.Descriptor instead.
func (*DomainStatusSyncTaskReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{2}
}

type DomainStatusSyncTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *DomainStatusSyncTaskReply) Reset() {
	*x = DomainStatusSyncTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainStatusSyncTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainStatusSyncTaskReply) ProtoMessage() {}

func (x *DomainStatusSyncTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainStatusSyncTaskReply.ProtoReflect.Descriptor instead.
func (*DomainStatusSyncTaskReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{3}
}

func (x *DomainStatusSyncTaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

type DomainLdapSyncTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DomainLdapSyncTaskReq) Reset() {
	*x = DomainLdapSyncTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainLdapSyncTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainLdapSyncTaskReq) ProtoMessage() {}

func (x *DomainLdapSyncTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainLdapSyncTaskReq.ProtoReflect.Descriptor instead.
func (*DomainLdapSyncTaskReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{4}
}

type DomainLdapSyncTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *DomainLdapSyncTaskReply) Reset() {
	*x = DomainLdapSyncTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DomainLdapSyncTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainLdapSyncTaskReply) ProtoMessage() {}

func (x *DomainLdapSyncTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainLdapSyncTaskReply.ProtoReflect.Descriptor instead.
func (*DomainLdapSyncTaskReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{5}
}

func (x *DomainLdapSyncTaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

// multi time to call this API for multi domain scanning task
type ScannerBaselineTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainTmplMap map[string]string `protobuf:"bytes,1,rep,name=domainTmplMap,proto3" json:"domainTmplMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ScannerBaselineTaskReq) Reset() {
	*x = ScannerBaselineTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerBaselineTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerBaselineTaskReq) ProtoMessage() {}

func (x *ScannerBaselineTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerBaselineTaskReq.ProtoReflect.Descriptor instead.
func (*ScannerBaselineTaskReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{6}
}

func (x *ScannerBaselineTaskReq) GetDomainTmplMap() map[string]string {
	if x != nil {
		return x.DomainTmplMap
	}
	return nil
}

type ScannerBaselineTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *ScannerBaselineTaskReply) Reset() {
	*x = ScannerBaselineTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerBaselineTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerBaselineTaskReply) ProtoMessage() {}

func (x *ScannerBaselineTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerBaselineTaskReply.ProtoReflect.Descriptor instead.
func (*ScannerBaselineTaskReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{7}
}

func (x *ScannerBaselineTaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

type ScannerLeakTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainTmplMap map[string]string `protobuf:"bytes,1,rep,name=domainTmplMap,proto3" json:"domainTmplMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ScannerLeakTaskReq) Reset() {
	*x = ScannerLeakTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerLeakTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerLeakTaskReq) ProtoMessage() {}

func (x *ScannerLeakTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerLeakTaskReq.ProtoReflect.Descriptor instead.
func (*ScannerLeakTaskReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{8}
}

func (x *ScannerLeakTaskReq) GetDomainTmplMap() map[string]string {
	if x != nil {
		return x.DomainTmplMap
	}
	return nil
}

type ScannerLeakTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *ScannerLeakTaskReply) Reset() {
	*x = ScannerLeakTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerLeakTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerLeakTaskReply) ProtoMessage() {}

func (x *ScannerLeakTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerLeakTaskReply.ProtoReflect.Descriptor instead.
func (*ScannerLeakTaskReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{9}
}

func (x *ScannerLeakTaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

type ScannerWeakPwdTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DomainTmplMap map[string]string `protobuf:"bytes,1,rep,name=domainTmplMap,proto3" json:"domainTmplMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ScannerWeakPwdTaskReq) Reset() {
	*x = ScannerWeakPwdTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerWeakPwdTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerWeakPwdTaskReq) ProtoMessage() {}

func (x *ScannerWeakPwdTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerWeakPwdTaskReq.ProtoReflect.Descriptor instead.
func (*ScannerWeakPwdTaskReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{10}
}

func (x *ScannerWeakPwdTaskReq) GetDomainTmplMap() map[string]string {
	if x != nil {
		return x.DomainTmplMap
	}
	return nil
}

type ScannerWeakPwdTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *ScannerWeakPwdTaskReply) Reset() {
	*x = ScannerWeakPwdTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerWeakPwdTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerWeakPwdTaskReply) ProtoMessage() {}

func (x *ScannerWeakPwdTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerWeakPwdTaskReply.ProtoReflect.Descriptor instead.
func (*ScannerWeakPwdTaskReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{11}
}

func (x *ScannerWeakPwdTaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

type ScannerRecheckTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScanType  string `protobuf:"bytes,1,opt,name=scanType,proto3" json:"scanType,omitempty"`   // baseline|leak|weakpwd
	SubTaskId string `protobuf:"bytes,2,opt,name=subTaskId,proto3" json:"subTaskId,omitempty"` // subtask_id
}

func (x *ScannerRecheckTaskReq) Reset() {
	*x = ScannerRecheckTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerRecheckTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerRecheckTaskReq) ProtoMessage() {}

func (x *ScannerRecheckTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerRecheckTaskReq.ProtoReflect.Descriptor instead.
func (*ScannerRecheckTaskReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{12}
}

func (x *ScannerRecheckTaskReq) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *ScannerRecheckTaskReq) GetSubTaskId() string {
	if x != nil {
		return x.SubTaskId
	}
	return ""
}

type ScannerRecheckTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *ScannerRecheckTaskReply) Reset() {
	*x = ScannerRecheckTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScannerRecheckTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScannerRecheckTaskReply) ProtoMessage() {}

func (x *ScannerRecheckTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScannerRecheckTaskReply.ProtoReflect.Descriptor instead.
func (*ScannerRecheckTaskReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{13}
}

func (x *ScannerRecheckTaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

type ExportReportTaskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`     // alert|baseline|leak|weakpwd|audit|...
	Params string `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"` // 参数 json
}

func (x *ExportReportTaskReq) Reset() {
	*x = ExportReportTaskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportReportTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportTaskReq) ProtoMessage() {}

func (x *ExportReportTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportTaskReq.ProtoReflect.Descriptor instead.
func (*ExportReportTaskReq) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{14}
}

func (x *ExportReportTaskReq) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *ExportReportTaskReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExportReportTaskReq) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type ExportReportTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID string `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
}

func (x *ExportReportTaskReply) Reset() {
	*x = ExportReportTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ada_task_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportReportTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportTaskReply) ProtoMessage() {}

func (x *ExportReportTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_ada_task_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportTaskReply.ProtoReflect.Descriptor instead.
func (*ExportReportTaskReply) Descriptor() ([]byte, []int) {
	return file_ada_task_proto_rawDescGZIP(), []int{15}
}

func (x *ExportReportTaskReply) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

var File_ada_task_proto protoreflect.FileDescriptor

var file_ada_task_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x64, 0x61, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x2d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b,
	0x55, 0x55, 0x49, 0x44, 0x22, 0x95, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61,
	0x73, 0x6b, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61,
	0x73, 0x6b, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x19, 0x0a, 0x17,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x79, 0x6e, 0x63,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x22, 0x33, 0x0a, 0x19, 0x44, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x17, 0x0a, 0x15,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4c, 0x64, 0x61, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x22, 0x31, 0x0a, 0x17, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4c,
	0x64, 0x61, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0xb0, 0x01, 0x0a, 0x16, 0x53, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x12, 0x54, 0x0a, 0x0d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x6d, 0x70,
	0x6c, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x6d,
	0x70, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x54, 0x6d, 0x70, 0x6c, 0x4d, 0x61, 0x70, 0x1a, 0x40, 0x0a, 0x12, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x54, 0x6d, 0x70, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x32, 0x0a, 0x18, 0x53,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22,
	0xa8, 0x01, 0x0a, 0x12, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x6b, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x50, 0x0a, 0x0d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x54, 0x6d, 0x70, 0x6c, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x6b, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x6d, 0x70,
	0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x54, 0x6d, 0x70, 0x6c, 0x4d, 0x61, 0x70, 0x1a, 0x40, 0x0a, 0x12, 0x44, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x54, 0x6d, 0x70, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2e, 0x0a, 0x14, 0x53, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0xae, 0x01, 0x0a, 0x15, 0x53,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x57, 0x65, 0x61, 0x6b, 0x50, 0x77, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x53, 0x0a, 0x0d, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x6d,
	0x70, 0x6c, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x57, 0x65, 0x61, 0x6b, 0x50, 0x77, 0x64,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x54, 0x6d,
	0x70, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x54, 0x6d, 0x70, 0x6c, 0x4d, 0x61, 0x70, 0x1a, 0x40, 0x0a, 0x12, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x54, 0x6d, 0x70, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x31, 0x0a, 0x17, 0x53,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x57, 0x65, 0x61, 0x6b, 0x50, 0x77, 0x64, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x22, 0x51,
	0x0a, 0x15, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x63, 0x61, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x63, 0x61, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x54, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x22, 0x31, 0x0a, 0x17, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x44, 0x22, 0x59, 0x0a, 0x13, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x73, 0x6b, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73,
	0x6b, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22,
	0x2f, 0x0a, 0x15, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x44,
	0x32, 0xf1, 0x04, 0x0a, 0x07, 0x41, 0x44, 0x41, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x3c, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x14, 0x44, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x4e, 0x0a, 0x12, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4c, 0x64, 0x61, 0x70, 0x53, 0x79,
	0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x4c, 0x64, 0x61, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4c,
	0x64, 0x61, 0x70, 0x53, 0x79, 0x6e, 0x63, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x51, 0x0a, 0x13, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x42, 0x61, 0x73, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x0f, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x65,
	0x61, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x65, 0x61, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x4c, 0x65, 0x61,
	0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x12, 0x53, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x57, 0x65, 0x61, 0x6b, 0x50, 0x77, 0x64, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x57, 0x65,
	0x61, 0x6b, 0x50, 0x77, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x57, 0x65, 0x61, 0x6b, 0x50, 0x77,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x12, 0x53, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x10, 0x45, 0x78,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x18,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ada_task_proto_rawDescOnce sync.Once
	file_ada_task_proto_rawDescData = file_ada_task_proto_rawDesc
)

func file_ada_task_proto_rawDescGZIP() []byte {
	file_ada_task_proto_rawDescOnce.Do(func() {
		file_ada_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_ada_task_proto_rawDescData)
	})
	return file_ada_task_proto_rawDescData
}

var file_ada_task_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ada_task_proto_goTypes = []interface{}{
	(*GetTaskStateReq)(nil),           // 0: api.GetTaskStateReq
	(*GetTaskStateReply)(nil),         // 1: api.GetTaskStateReply
	(*DomainStatusSyncTaskReq)(nil),   // 2: api.DomainStatusSyncTaskReq
	(*DomainStatusSyncTaskReply)(nil), // 3: api.DomainStatusSyncTaskReply
	(*DomainLdapSyncTaskReq)(nil),     // 4: api.DomainLdapSyncTaskReq
	(*DomainLdapSyncTaskReply)(nil),   // 5: api.DomainLdapSyncTaskReply
	(*ScannerBaselineTaskReq)(nil),    // 6: api.ScannerBaselineTaskReq
	(*ScannerBaselineTaskReply)(nil),  // 7: api.ScannerBaselineTaskReply
	(*ScannerLeakTaskReq)(nil),        // 8: api.ScannerLeakTaskReq
	(*ScannerLeakTaskReply)(nil),      // 9: api.ScannerLeakTaskReply
	(*ScannerWeakPwdTaskReq)(nil),     // 10: api.ScannerWeakPwdTaskReq
	(*ScannerWeakPwdTaskReply)(nil),   // 11: api.ScannerWeakPwdTaskReply
	(*ScannerRecheckTaskReq)(nil),     // 12: api.ScannerRecheckTaskReq
	(*ScannerRecheckTaskReply)(nil),   // 13: api.ScannerRecheckTaskReply
	(*ExportReportTaskReq)(nil),       // 14: api.ExportReportTaskReq
	(*ExportReportTaskReply)(nil),     // 15: api.ExportReportTaskReply
	nil,                               // 16: api.ScannerBaselineTaskReq.DomainTmplMapEntry
	nil,                               // 17: api.ScannerLeakTaskReq.DomainTmplMapEntry
	nil,                               // 18: api.ScannerWeakPwdTaskReq.DomainTmplMapEntry
}
var file_ada_task_proto_depIdxs = []int32{
	16, // 0: api.ScannerBaselineTaskReq.domainTmplMap:type_name -> api.ScannerBaselineTaskReq.DomainTmplMapEntry
	17, // 1: api.ScannerLeakTaskReq.domainTmplMap:type_name -> api.ScannerLeakTaskReq.DomainTmplMapEntry
	18, // 2: api.ScannerWeakPwdTaskReq.domainTmplMap:type_name -> api.ScannerWeakPwdTaskReq.DomainTmplMapEntry
	0,  // 3: api.ADATask.GetTaskState:input_type -> api.GetTaskStateReq
	2,  // 4: api.ADATask.DomainStatusSyncTask:input_type -> api.DomainStatusSyncTaskReq
	4,  // 5: api.ADATask.DomainLdapSyncTask:input_type -> api.DomainLdapSyncTaskReq
	6,  // 6: api.ADATask.ScannerBaselineTask:input_type -> api.ScannerBaselineTaskReq
	8,  // 7: api.ADATask.ScannerLeakTask:input_type -> api.ScannerLeakTaskReq
	10, // 8: api.ADATask.ScannerWeakPwdTask:input_type -> api.ScannerWeakPwdTaskReq
	12, // 9: api.ADATask.ScannerRecheckTask:input_type -> api.ScannerRecheckTaskReq
	14, // 10: api.ADATask.ExportReportTask:input_type -> api.ExportReportTaskReq
	1,  // 11: api.ADATask.GetTaskState:output_type -> api.GetTaskStateReply
	3,  // 12: api.ADATask.DomainStatusSyncTask:output_type -> api.DomainStatusSyncTaskReply
	5,  // 13: api.ADATask.DomainLdapSyncTask:output_type -> api.DomainLdapSyncTaskReply
	7,  // 14: api.ADATask.ScannerBaselineTask:output_type -> api.ScannerBaselineTaskReply
	9,  // 15: api.ADATask.ScannerLeakTask:output_type -> api.ScannerLeakTaskReply
	11, // 16: api.ADATask.ScannerWeakPwdTask:output_type -> api.ScannerWeakPwdTaskReply
	13, // 17: api.ADATask.ScannerRecheckTask:output_type -> api.ScannerRecheckTaskReply
	15, // 18: api.ADATask.ExportReportTask:output_type -> api.ExportReportTaskReply
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ada_task_proto_init() }
func file_ada_task_proto_init() {
	if File_ada_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ada_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskStateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTaskStateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainStatusSyncTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainStatusSyncTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainLdapSyncTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DomainLdapSyncTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerBaselineTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerBaselineTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerLeakTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerLeakTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerWeakPwdTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerWeakPwdTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerRecheckTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScannerRecheckTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportReportTaskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ada_task_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportReportTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ada_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ada_task_proto_goTypes,
		DependencyIndexes: file_ada_task_proto_depIdxs,
		MessageInfos:      file_ada_task_proto_msgTypes,
	}.Build()
	File_ada_task_proto = out.File
	file_ada_task_proto_rawDesc = nil
	file_ada_task_proto_goTypes = nil
	file_ada_task_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ADATaskClient is the client API for ADATask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ADATaskClient interface {
	// tasker内部接口
	GetTaskState(ctx context.Context, in *GetTaskStateReq, opts ...grpc.CallOption) (*GetTaskStateReply, error)
	// 域名相关任务
	DomainStatusSyncTask(ctx context.Context, in *DomainStatusSyncTaskReq, opts ...grpc.CallOption) (*DomainStatusSyncTaskReply, error)
	DomainLdapSyncTask(ctx context.Context, in *DomainLdapSyncTaskReq, opts ...grpc.CallOption) (*DomainLdapSyncTaskReply, error)
	// 扫描器相关任务
	ScannerBaselineTask(ctx context.Context, in *ScannerBaselineTaskReq, opts ...grpc.CallOption) (*ScannerBaselineTaskReply, error)
	ScannerLeakTask(ctx context.Context, in *ScannerLeakTaskReq, opts ...grpc.CallOption) (*ScannerLeakTaskReply, error)
	ScannerWeakPwdTask(ctx context.Context, in *ScannerWeakPwdTaskReq, opts ...grpc.CallOption) (*ScannerWeakPwdTaskReply, error)
	ScannerRecheckTask(ctx context.Context, in *ScannerRecheckTaskReq, opts ...grpc.CallOption) (*ScannerRecheckTaskReply, error)
	// 导出任务
	ExportReportTask(ctx context.Context, in *ExportReportTaskReq, opts ...grpc.CallOption) (*ExportReportTaskReply, error)
}

type aDATaskClient struct {
	cc grpc.ClientConnInterface
}

func NewADATaskClient(cc grpc.ClientConnInterface) ADATaskClient {
	return &aDATaskClient{cc}
}

func (c *aDATaskClient) GetTaskState(ctx context.Context, in *GetTaskStateReq, opts ...grpc.CallOption) (*GetTaskStateReply, error) {
	out := new(GetTaskStateReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/GetTaskState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aDATaskClient) DomainStatusSyncTask(ctx context.Context, in *DomainStatusSyncTaskReq, opts ...grpc.CallOption) (*DomainStatusSyncTaskReply, error) {
	out := new(DomainStatusSyncTaskReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/DomainStatusSyncTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aDATaskClient) DomainLdapSyncTask(ctx context.Context, in *DomainLdapSyncTaskReq, opts ...grpc.CallOption) (*DomainLdapSyncTaskReply, error) {
	out := new(DomainLdapSyncTaskReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/DomainLdapSyncTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aDATaskClient) ScannerBaselineTask(ctx context.Context, in *ScannerBaselineTaskReq, opts ...grpc.CallOption) (*ScannerBaselineTaskReply, error) {
	out := new(ScannerBaselineTaskReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/ScannerBaselineTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aDATaskClient) ScannerLeakTask(ctx context.Context, in *ScannerLeakTaskReq, opts ...grpc.CallOption) (*ScannerLeakTaskReply, error) {
	out := new(ScannerLeakTaskReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/ScannerLeakTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aDATaskClient) ScannerWeakPwdTask(ctx context.Context, in *ScannerWeakPwdTaskReq, opts ...grpc.CallOption) (*ScannerWeakPwdTaskReply, error) {
	out := new(ScannerWeakPwdTaskReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/ScannerWeakPwdTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aDATaskClient) ScannerRecheckTask(ctx context.Context, in *ScannerRecheckTaskReq, opts ...grpc.CallOption) (*ScannerRecheckTaskReply, error) {
	out := new(ScannerRecheckTaskReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/ScannerRecheckTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aDATaskClient) ExportReportTask(ctx context.Context, in *ExportReportTaskReq, opts ...grpc.CallOption) (*ExportReportTaskReply, error) {
	out := new(ExportReportTaskReply)
	err := c.cc.Invoke(ctx, "/api.ADATask/ExportReportTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ADATaskServer is the server API for ADATask service.
type ADATaskServer interface {
	// tasker内部接口
	GetTaskState(context.Context, *GetTaskStateReq) (*GetTaskStateReply, error)
	// 域名相关任务
	DomainStatusSyncTask(context.Context, *DomainStatusSyncTaskReq) (*DomainStatusSyncTaskReply, error)
	DomainLdapSyncTask(context.Context, *DomainLdapSyncTaskReq) (*DomainLdapSyncTaskReply, error)
	// 扫描器相关任务
	ScannerBaselineTask(context.Context, *ScannerBaselineTaskReq) (*ScannerBaselineTaskReply, error)
	ScannerLeakTask(context.Context, *ScannerLeakTaskReq) (*ScannerLeakTaskReply, error)
	ScannerWeakPwdTask(context.Context, *ScannerWeakPwdTaskReq) (*ScannerWeakPwdTaskReply, error)
	ScannerRecheckTask(context.Context, *ScannerRecheckTaskReq) (*ScannerRecheckTaskReply, error)
	// 导出任务
	ExportReportTask(context.Context, *ExportReportTaskReq) (*ExportReportTaskReply, error)
}

// UnimplementedADATaskServer can be embedded to have forward compatible implementations.
type UnimplementedADATaskServer struct {
}

func (*UnimplementedADATaskServer) GetTaskState(context.Context, *GetTaskStateReq) (*GetTaskStateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskState not implemented")
}
func (*UnimplementedADATaskServer) DomainStatusSyncTask(context.Context, *DomainStatusSyncTaskReq) (*DomainStatusSyncTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainStatusSyncTask not implemented")
}
func (*UnimplementedADATaskServer) DomainLdapSyncTask(context.Context, *DomainLdapSyncTaskReq) (*DomainLdapSyncTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DomainLdapSyncTask not implemented")
}
func (*UnimplementedADATaskServer) ScannerBaselineTask(context.Context, *ScannerBaselineTaskReq) (*ScannerBaselineTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScannerBaselineTask not implemented")
}
func (*UnimplementedADATaskServer) ScannerLeakTask(context.Context, *ScannerLeakTaskReq) (*ScannerLeakTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScannerLeakTask not implemented")
}
func (*UnimplementedADATaskServer) ScannerWeakPwdTask(context.Context, *ScannerWeakPwdTaskReq) (*ScannerWeakPwdTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScannerWeakPwdTask not implemented")
}
func (*UnimplementedADATaskServer) ScannerRecheckTask(context.Context, *ScannerRecheckTaskReq) (*ScannerRecheckTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScannerRecheckTask not implemented")
}
func (*UnimplementedADATaskServer) ExportReportTask(context.Context, *ExportReportTaskReq) (*ExportReportTaskReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportReportTask not implemented")
}

func RegisterADATaskServer(s *grpc.Server, srv ADATaskServer) {
	s.RegisterService(&_ADATask_serviceDesc, srv)
}

func _ADATask_GetTaskState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).GetTaskState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/GetTaskState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).GetTaskState(ctx, req.(*GetTaskStateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ADATask_DomainStatusSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainStatusSyncTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).DomainStatusSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/DomainStatusSyncTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).DomainStatusSyncTask(ctx, req.(*DomainStatusSyncTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ADATask_DomainLdapSyncTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainLdapSyncTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).DomainLdapSyncTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/DomainLdapSyncTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).DomainLdapSyncTask(ctx, req.(*DomainLdapSyncTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ADATask_ScannerBaselineTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScannerBaselineTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).ScannerBaselineTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/ScannerBaselineTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).ScannerBaselineTask(ctx, req.(*ScannerBaselineTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ADATask_ScannerLeakTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScannerLeakTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).ScannerLeakTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/ScannerLeakTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).ScannerLeakTask(ctx, req.(*ScannerLeakTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ADATask_ScannerWeakPwdTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScannerWeakPwdTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).ScannerWeakPwdTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/ScannerWeakPwdTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).ScannerWeakPwdTask(ctx, req.(*ScannerWeakPwdTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ADATask_ScannerRecheckTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScannerRecheckTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).ScannerRecheckTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/ScannerRecheckTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).ScannerRecheckTask(ctx, req.(*ScannerRecheckTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ADATask_ExportReportTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReportTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ADATaskServer).ExportReportTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ADATask/ExportReportTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ADATaskServer).ExportReportTask(ctx, req.(*ExportReportTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ADATask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ADATask",
	HandlerType: (*ADATaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskState",
			Handler:    _ADATask_GetTaskState_Handler,
		},
		{
			MethodName: "DomainStatusSyncTask",
			Handler:    _ADATask_DomainStatusSyncTask_Handler,
		},
		{
			MethodName: "DomainLdapSyncTask",
			Handler:    _ADATask_DomainLdapSyncTask_Handler,
		},
		{
			MethodName: "ScannerBaselineTask",
			Handler:    _ADATask_ScannerBaselineTask_Handler,
		},
		{
			MethodName: "ScannerLeakTask",
			Handler:    _ADATask_ScannerLeakTask_Handler,
		},
		{
			MethodName: "ScannerWeakPwdTask",
			Handler:    _ADATask_ScannerWeakPwdTask_Handler,
		},
		{
			MethodName: "ScannerRecheckTask",
			Handler:    _ADATask_ScannerRecheckTask_Handler,
		},
		{
			MethodName: "ExportReportTask",
			Handler:    _ADATask_ExportReportTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ada_task.proto",
}
