// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ada_task.proto

package api

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetTaskStateReq) Validate() error {
	return nil
}
func (this *GetTaskStateReply) Validate() error {
	return nil
}
func (this *DomainStatusSyncTaskReq) Validate() error {
	return nil
}
func (this *DomainStatusSyncTaskReply) Validate() error {
	return nil
}
func (this *DomainLdapSyncTaskReq) Validate() error {
	return nil
}
func (this *DomainLdapSyncTaskReply) Validate() error {
	return nil
}
func (this *ScannerBaselineTaskReq) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ScannerBaselineTaskReply) Validate() error {
	return nil
}
func (this *ScannerLeakTaskReq) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ScannerLeakTaskReply) Validate() error {
	return nil
}
func (this *ScannerWeakPwdTaskReq) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ScannerWeakPwdTaskReply) Validate() error {
	return nil
}
func (this *ScannerRecheckTaskReq) Validate() error {
	return nil
}
func (this *ScannerRecheckTaskReply) Validate() error {
	return nil
}
func (this *ExportReportTaskReq) Validate() error {
	return nil
}
func (this *ExportReportTaskReply) Validate() error {
	return nil
}
