
services:
  ada_mongodb:
    container_name: "ada_mongodb"
    image: ada_mongodb:2.9.1
    restart: unless-stopped
    networks:
      - ada-networks
    environment:
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="XEl44B4p3hFurztFMo38"
    volumes:
      - /home/adadmin/data/mongodb:/data/db:rw
      - /home/adadmin/logs/mongodb:/var/log/mongodb:rw
    ports:
      - "27017:27017/tcp"

  ada_redis:
    container_name: "ada_redis"
    image: ada_redis:2.9.1
    restart: unless-stopped
    networks:
      - ada-networks
    volumes:
      - /home/adadmin/data/redis:/data:rw
    ports:
      - "9091:9091/tcp"
      - "6379:6379/tcp"

  # ada_elasticsearch:
  #   container_name: "ada_elasticsearch"
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
  #   restart: unless-stopped
  #   networks:
  #     - ada-networks
  #   volumes:
  #     - /home/adadmin/data/elasticsearch:/usr/share/elasticsearch/data
  #     - /home/adadmin/logs/elasticsearch:/var/log/elasticsearch
  #   ports:
  #     - "9200:9200"
  #   environment:
  #     - cluster.name=elasticsearch
  #     - discovery.type=single-node
  #     - network.host=0.0.0.0
  #     - xpack.security.enabled=true
  #     - xpack.security.http.ssl.enabled=false
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - ELASTIC_PASSWORD="nX0ZIN0AIfFs5x=fZfuE"
  #     - KIBANA_SYSTEM_PASSWORD="nX0ZIN0AIfFs5x=fZfuE"
  #   healthcheck:
  #     test: ['CMD-SHELL', 'curl --silent --fail localhost:9200/_cluster/health || exit 1']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 30s
  #   mem_limit: 8G
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1

  # ada_kibana:
  #   container_name: "ada_kibana"
  #   image: docker.elastic.co/kibana/kibana:8.14.3
  #   restart: unless-stopped
  #   user: "1002:1002"
  #   networks:
  #     - ada-networks
  #   # volumes:
  #   #   - /home/adadmin/conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - ada_elasticsearch

  # ada_backend:
  #   container_name: "ada_backend"
  #   image: ada_backend:2.9.1
  #   restart: unless-stopped
  #   networks:
  #     - ada-networks
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /home/adadmin/logs/nginx:/var/log/nginx
  #     - /home/adadmin/logs/supervisor:/var/log/supervisor
  #     - /home/adadmin/logs/backend:/home/adadmin/logs
  #   depends_on:
  #     - ada_elasticsearch
  #     - ada_redis
  #     - ada_mongodb

  # ada_zeek:
  #   container_name: "ada_zeek"
  #   image: ada_zeek:2.9.1
  #   restart: unless-stopped
  #   networks:
  #     - ada-networks
  #   ports:
  #     - "9093:9093/udp"
  #   depends_on:
  #     - ada_elasticsearch
  #     - ada_redis
  #     - ada_backend

  # ada_scanner:
  #   container_name: "ada_scanner"
  #   image: ada_scanner:2.9.1
  #   restart: unless-stopped
  #   networks:
  #     - ada-networks
  #   volumes:
  #     - /home/adadmin/logs/scanner:/home/adadmin/logs:Z
  #   depends_on:
  #     - ada_mongodb
  #     - ada_redis

# define docker network
networks:
  ada-networks:

volumes:
  es_data:
    driver: local
