[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
user=root
logfile=/home/adadmin/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/home/adadmin/logs

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:easytier]
directory=/home/adadmin/bin
command=/home/adadmin/bin/easytier-core --no-tun --socks5 1080 --port-forward tcp://127.0.0.1:5601/192.168.9.3:5601 --port-forward tcp://127.0.0.1:9200/192.168.9.3:9200 -c /home/adadmin/conf/easytier.toml
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/easytier_stderr.log
stdout_logfile=/home/adadmin/logs/easytier_stdout.log
stderr_logfile_backups=3
numprocs=1
priority=100
numprocs_start=0
user=root

[program:apiserver]
directory=/home/adadmin/bin
command=/home/adadmin/bin/apiserver
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/apiserver_stderr.log
stdout_logfile=/home/adadmin/logs/apiserver_stdout.log
stderr_logfile_backups=3
numprocs=1
priority=105
numprocs_start=0
user=adadmin

[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
priority=200
user=root
