Panic Soft
#NoFreeOnExit TRUE

define ROOT     C:\Program Files\nxlog
define CERTDIR  %ROOT%\cert
define CONFDIR  %ROOT%\conf\nxlog.d
define LOGDIR   %ROOT%\data

include %CONFDIR%\\*.conf
define LOGFILE  %LOGDIR%\nxlog.log
LogFile %LOGFILE%

Moduledir %ROOT%\modules
CacheDir  %ROOT%\data
Pidfile   %ROOT%\data\nxlog.pid
SpoolDir  %ROOT%\data

<Extension json>
    Module      xm_json
</Extension>

<Extension syslog>
    Module      xm_syslog
</Extension>

<Input eventlog>
    Module      im_msvistalog
    Query       <QueryList>\
                    <Query Id="0">\
                        <Select Path="Application">*</Select>\
                        <Select Path="System">*</Select>\
                        <Select Path="Security">*</Select>\
                        <Select Path="RPCFW">*</Select>\
                        <Select Path="LDAPFW">*</Select>\
                        <Select Path="Directory Service">*</Select>\
                        <Select Path="Microsoft-Windows-PowerShell/Operational">*</Select>\
                        <Select Path="Microsoft-Windows-TaskScheduler/Operational">*</Select>\
                        <Select Path="Microsoft-Windows-WMI-Activity/Operational">*</Select>\
                        <Select Path="Microsoft-Windows-SMBClient/Security">*</Select>\
                        <Select Path="Microsoft-Windows-TerminalServices-RDPClient/Operational">*</Select>\
                        <Select Path="Microsoft-Windows-TerminalServices-LocalSessionManager/Operational">*</Select>\
                        <Select Path="Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational">*</Select>\
                    </Query>\
                </QueryList>
#    <Exec>
#        if not ($EventID in (12345, 22222))
#        drop();
#    </Exec>
    <Exec>
        if (
            (defined($ProcessName) and $ProcessName =~ /WmiPrvSE.exe/)
            or ($EventID in (1, 4690))
        )
        drop();
    </Exec>
</Input>


<Output out_adasrv>
    Module      om_udp
    Host        192.168.18.4
    Port        9091
    Exec        $Hostname = hostname_fqdn();
    Exec        delete($SourceModuleType);
    Exec        delete($SourceModuleName);
    Exec        delete($Keywords);
    Exec        $now = integer(now())/1000; rename_field("now", "@timestamp");
    Exec        $Message = to_json(); to_syslog_bsd();
</Output>


<Route 1>
    Path        eventlog => out_adasrv
</Route>