[program:ada_apiserver]
environment=APISERVER_CONF_PATH=./apiserver_local.yaml
directory=/home/adaegis/ada/bin
command=/home/adaegis/ada/bin/apiserver
autorestart=true
autostart=true
stderr_logfile=/home/adaegis/logs/apiserver_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=105
numprocs_start=0
user=adaegis