[program:ada_receiver]
environment=RECEIVER_CONF_PATH=./receiver_local.yaml
directory=/home/adaegis/ada/bin
command=/home/adaegis/ada/bin/receiver
autorestart=true
autostart=true
stderr_logfile=/home/adaegis/logs/receiver_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=100
numprocs_start=0
user=adaegis