[program:ada_ruleserver]
directory=/home/adadmin/bin
command=/home/adadmin/bin/rule_server
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/ruleserver_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=105
numprocs_start=0
user=adadmin