[program:ada_apiserver]
environment=APISERVER_CONF_PATH=./apiserver.yaml
directory=/home/adadmin/bin
command=/home/adadmin/bin/apiserver
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/apiserver_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=105
numprocs_start=0
user=adadmin