[program:ada_scanner]
environment=SCANNER_CONF_PATH=./scanner.yaml
directory=/home/adadmin/bin
command=/home/adadmin/bin/scanner
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/scanner_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=101
numprocs_start=0
user=adadmin