[program:ada_engine]
environment=ENGINE_CONF_PATH=./engine_local.yaml
directory=/home/adaegis/ada/bin
command=/home/adaegis/ada/bin/engine
autorestart=true
autostart=true
stderr_logfile=/home/adaegis/logs/engine_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=102
numprocs_start=0
user=adaegis