[program:ada_taskserver]
environment=TASKER_CONF_PATH=./tasker.yaml
directory=/home/adadmin/bin
command=/home/adadmin/bin/task_server
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/taskserver_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=103
numprocs_start=0
user=adadmin