[program:ada_scanner]
environment=SCANNER_CONF_PATH=./scanner_local.yaml
directory=/home/adaegis/ada/bin
command=/home/adaegis/ada/bin/scanner
autorestart=true
autostart=true
stderr_logfile=/home/adaegis/logs/scanner_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=101
numprocs_start=0
user=adaegis