[program:ada_engine]
environment=ENGINE_CONF_PATH=./engine.yaml
directory=/home/adadmin/bin
command=/home/adadmin/bin/engine
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/engine_stderr.log
stderr_logfile_backups=1
numprocs=1
priority=102
numprocs_start=0
user=adadmin