[program:ada_taskworker]
environment=TASKER_CONF_PATH=./tasker_local.yaml
directory=/home/adaegis/ada/bin
command=/home/adaegis/ada/bin/task_worker
autorestart=true
autostart=true
stderr_logfile=/home/adaegis/logs/taskworker_stderr.log
stdout_logfile=/home/adaegis/logs/taskworker_stdout.log
stdout_logfile_backups=1
stderr_logfile_backups=1
numprocs=1
priority=104
numprocs_start=0
user=adaegis