# Stream proxy for Redis and MongoDB (portal only)
stream {
    # Redis proxy
    upstream redis_backend {
        server ada-poc-redis-redis.ns-x7n5f7v4.svc:6379;
    }

    server {
        listen 6379;
        proxy_pass redis_backend;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
    }

    # MongoDB proxy
    upstream mongodb_backend {
        server ada-poc-db-mongodb.ns-x7n5f7v4.svc:27017;
    }

    server {
        listen 27017;
        proxy_pass mongodb_backend;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
    }
}
