[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
user=root
logfile=/home/adadmin/logs/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/home/adadmin/logs

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:taskserver]
directory=/home/adadmin/bin
command=/home/adadmin/bin/task_server
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/taskserver_stderr.log
stdout_logfile=/home/adadmin/logs/taskserver_stdout.log
stderr_logfile_backups=3
numprocs=1
priority=103
numprocs_start=0
user=adadmin

[program:taskworker]
directory=/home/adadmin/bin
command=/home/adadmin/bin/task_worker
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/taskworker_stderr.log
stdout_logfile=/home/adadmin/logs/taskworker_stdout.log
stderr_logfile_backups=3
numprocs=1
priority=104
numprocs_start=0
user=adadmin

[program:apiserver]
directory=/home/adadmin/bin
command=/home/adadmin/bin/apiserver
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/apiserver_stderr.log
stdout_logfile=/home/adadmin/logs/apiserver_stdout.log
stderr_logfile_backups=3
numprocs=1
priority=105
numprocs_start=0
user=adadmin

[program:engine]
directory=/home/adadmin/bin
command=/home/adadmin/bin/engine
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/engine_stderr.log
stdout_logfile=/home/adadmin/logs/engine_stdout.log
stderr_logfile_backups=3
numprocs=1
priority=106
numprocs_start=0
user=adadmin

[program:frps]
directory=/home/adadmin/bin
command=/home/adadmin/bin/frps -c /home/adadmin/conf/frps.ini
autorestart=true
autostart=true
stderr_logfile=/home/adadmin/logs/frps_stderr.log
stdout_logfile=/home/adadmin/logs/frps_stdout.log
stderr_logfile_backups=3
numprocs=1
priority=102
numprocs_start=0
user=adadmin

[program:nginx]
command=nginx -g 'daemon off;'
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
user=root
