// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ada.proto

package v2

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	regexp "regexp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ModelPage) Validate() error {
	return nil
}

var _regex_LoginReq_TotpCode = regexp.MustCompile(`d{6}|^(\s&&[^\f\n\r\t\v])*`)

func (this *LoginReq) Validate() error {
	if this.Username == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Username", fmt.Errorf(`value '%v' must not be an empty string`, this.Username))
	}
	if this.Password == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Password", fmt.Errorf(`value '%v' must not be an empty string`, this.Password))
	}
	if !_regex_LoginReq_TotpCode.MatchString(this.TotpCode) {
		return github_com_mwitkow_go_proto_validators.FieldError("TotpCode", fmt.Errorf(`value '%v' must be a string conforming to regex "d{6}|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.TotpCode))
	}
	return nil
}
func (this *LoginReply) Validate() error {
	return nil
}
func (this *LogoutReq) Validate() error {
	return nil
}
func (this *LogoutReply) Validate() error {
	return nil
}
func (this *ListUserReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListUserReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListUserReply_Details) Validate() error {
	return nil
}

var _regex_AddUserReq_Mobile = regexp.MustCompile(`^1[3|4|5|6|7|8|9][0-9]\d{8}$|^(\s&&[^\f\n\r\t\v])*`)
var _regex_AddUserReq_Email = regexp.MustCompile(`\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*|^(\s&&[^\f\n\r\t\v])*`)

func (this *AddUserReq) Validate() error {
	if !_regex_AddUserReq_Mobile.MatchString(this.Mobile) {
		return github_com_mwitkow_go_proto_validators.FieldError("Mobile", fmt.Errorf(`value '%v' must be a string conforming to regex "^1[3|4|5|6|7|8|9][0-9]\\d{8}$|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.Mobile))
	}
	if !_regex_AddUserReq_Email.MatchString(this.Email) {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must be a string conforming to regex "\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.Email))
	}
	return nil
}
func (this *AddUserReply) Validate() error {
	return nil
}

var _regex_UpdateUserReq_Mobile = regexp.MustCompile(`^1[3|4|5|6|7|8|9][0-9]\d{8}$|^(\s&&[^\f\n\r\t\v])*`)
var _regex_UpdateUserReq_Email = regexp.MustCompile(`\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*|^(\s&&[^\f\n\r\t\v])*`)

func (this *UpdateUserReq) Validate() error {
	if !_regex_UpdateUserReq_Mobile.MatchString(this.Mobile) {
		return github_com_mwitkow_go_proto_validators.FieldError("Mobile", fmt.Errorf(`value '%v' must be a string conforming to regex "^1[3|4|5|6|7|8|9][0-9]\\d{8}$|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.Mobile))
	}
	if !_regex_UpdateUserReq_Email.MatchString(this.Email) {
		return github_com_mwitkow_go_proto_validators.FieldError("Email", fmt.Errorf(`value '%v' must be a string conforming to regex "\\w+([-+.]\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.Email))
	}
	return nil
}
func (this *UpdateUserReply) Validate() error {
	return nil
}
func (this *UpdateUserPasswordReq) Validate() error {
	return nil
}
func (this *UpdateUserPasswordReply) Validate() error {
	return nil
}
func (this *DeleteUserReq) Validate() error {
	return nil
}
func (this *DeleteUserReply) Validate() error {
	return nil
}
func (this *UserExistsReq) Validate() error {
	return nil
}
func (this *UserExistsReply) Validate() error {
	return nil
}
func (this *CheckMfaReq) Validate() error {
	return nil
}
func (this *CheckMfaReply) Validate() error {
	return nil
}
func (this *EnableMfaReq) Validate() error {
	if !(len(this.MfaCode) == 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("MfaCode", fmt.Errorf(`value '%v' must have a length equal to '6'`, this.MfaCode))
	}
	return nil
}
func (this *EnableMfaReply) Validate() error {
	return nil
}
func (this *DisableMfaReq) Validate() error {
	return nil
}
func (this *DisableMfaReply) Validate() error {
	return nil
}
func (this *UpdateAvatarReq) Validate() error {
	return nil
}
func (this *UpdateAvatarReply) Validate() error {
	return nil
}
func (this *ResetPasswordReq) Validate() error {
	if !(len(this.NewPassword) > 11) {
		return github_com_mwitkow_go_proto_validators.FieldError("NewPassword", fmt.Errorf(`value '%v' must have a length greater than '11'`, this.NewPassword))
	}
	return nil
}
func (this *ResetPasswordReply) Validate() error {
	return nil
}
func (this *ListDomainReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListDomainReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListDomainReplyDcList) Validate() error {
	return nil
}
func (this *ListDomainReply_Details) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	for _, item := range this.DCs {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("DCs", err)
			}
		}
	}
	return nil
}

var _regex_AddDomainReq_DNS = regexp.MustCompile(`^((0|[1-9]\d?|1\d\d|2[0-4]\d|25[0-5])\.){3}(0|[1-9]\d?|1\d\d|2[0-4]\d|25[0-5])$|^(\s&&[^\f\n\r\t\v])*`)

func (this *AddDomainReq) Validate() error {
	if !_regex_AddDomainReq_DNS.MatchString(this.DNS) {
		return github_com_mwitkow_go_proto_validators.FieldError("DNS", fmt.Errorf(`value '%v' must be a string conforming to regex "^((0|[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(0|[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-5])$|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.DNS))
	}
	return nil
}
func (this *AddDomainReply) Validate() error {
	return nil
}

var _regex_TestDomainReq_DNS = regexp.MustCompile(`^((0|[1-9]\d?|1\d\d|2[0-4]\d|25[0-5])\.){3}(0|[1-9]\d?|1\d\d|2[0-4]\d|25[0-5])$|^(\s&&[^\f\n\r\t\v])*`)

func (this *TestDomainReq) Validate() error {
	if !_regex_TestDomainReq_DNS.MatchString(this.DNS) {
		return github_com_mwitkow_go_proto_validators.FieldError("DNS", fmt.Errorf(`value '%v' must be a string conforming to regex "^((0|[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(0|[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-5])$|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.DNS))
	}
	return nil
}
func (this *TestDomainReply) Validate() error {
	return nil
}

var _regex_UpdateDomainReq_DNS = regexp.MustCompile(`^((0|[1-9]\d?|1\d\d|2[0-4]\d|25[0-5])\.){3}(0|[1-9]\d?|1\d\d|2[0-4]\d|25[0-5])$|^(\s&&[^\f\n\r\t\v])*`)

func (this *UpdateDomainReq) Validate() error {
	if !_regex_UpdateDomainReq_DNS.MatchString(this.DNS) {
		return github_com_mwitkow_go_proto_validators.FieldError("DNS", fmt.Errorf(`value '%v' must be a string conforming to regex "^((0|[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-5])\\.){3}(0|[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-5])$|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.DNS))
	}
	return nil
}
func (this *UpdateDomainReply) Validate() error {
	return nil
}
func (this *DeleteDomainReq) Validate() error {
	return nil
}
func (this *DeleteDomainReply) Validate() error {
	return nil
}
func (this *UpdateDomainDataReq) Validate() error {
	return nil
}
func (this *UpdateDomainDataReply) Validate() error {
	return nil
}
func (this *DeploySensorReq) Validate() error {
	return nil
}
func (this *DeploySensorReply) Validate() error {
	return nil
}
func (this *ListSensorReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListSensorReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListSensorReplyMapSlice) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ListSensorReply_Details) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	for _, item := range this.Events {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Events", err)
			}
		}
	}
	return nil
}

var _regex_UpdateSensorReq_PktPluginSwitch = regexp.MustCompile(`true|false`)
var _regex_UpdateSensorReq_LogPluginSwitch = regexp.MustCompile(`true|false`)
var _regex_UpdateSensorReq_RpcFwPluginSwitch = regexp.MustCompile(`true|false`)
var _regex_UpdateSensorReq_LdapFwPluginSwitch = regexp.MustCompile(`true|false`)

func (this *UpdateSensorReq) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	if !_regex_UpdateSensorReq_PktPluginSwitch.MatchString(this.PktPluginSwitch) {
		return github_com_mwitkow_go_proto_validators.FieldError("PktPluginSwitch", fmt.Errorf(`value '%v' must be a string conforming to regex "true|false"`, this.PktPluginSwitch))
	}
	if !_regex_UpdateSensorReq_LogPluginSwitch.MatchString(this.LogPluginSwitch) {
		return github_com_mwitkow_go_proto_validators.FieldError("LogPluginSwitch", fmt.Errorf(`value '%v' must be a string conforming to regex "true|false"`, this.LogPluginSwitch))
	}
	if !_regex_UpdateSensorReq_RpcFwPluginSwitch.MatchString(this.RpcFwPluginSwitch) {
		return github_com_mwitkow_go_proto_validators.FieldError("RpcFwPluginSwitch", fmt.Errorf(`value '%v' must be a string conforming to regex "true|false"`, this.RpcFwPluginSwitch))
	}
	if !_regex_UpdateSensorReq_LdapFwPluginSwitch.MatchString(this.LdapFwPluginSwitch) {
		return github_com_mwitkow_go_proto_validators.FieldError("LdapFwPluginSwitch", fmt.Errorf(`value '%v' must be a string conforming to regex "true|false"`, this.LdapFwPluginSwitch))
	}
	return nil
}
func (this *UpdateSensorReply) Validate() error {
	return nil
}

var _regex_DownloadSensorReq_Type = regexp.MustCompile(`x64|x86`)

func (this *DownloadSensorReq) Validate() error {
	if !_regex_DownloadSensorReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "x64|x86"`, this.Type))
	}
	return nil
}
func (this *DownloadSensorReply) Validate() error {
	return nil
}

var _regex_CmdSensorReq_Cmd = regexp.MustCompile(`delete|uninstall`)

func (this *CmdSensorReq) Validate() error {
	if !_regex_CmdSensorReq_Cmd.MatchString(this.Cmd) {
		return github_com_mwitkow_go_proto_validators.FieldError("Cmd", fmt.Errorf(`value '%v' must be a string conforming to regex "delete|uninstall"`, this.Cmd))
	}
	return nil
}
func (this *CmdSensorReply) Validate() error {
	return nil
}
func (this *UpdateSensorVersionReq) Validate() error {
	return nil
}
func (this *UpdateSensorVersionReply) Validate() error {
	return nil
}
func (this *GetSystemInfoReq) Validate() error {
	return nil
}
func (this *GetSystemInfoReply) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	if this.SystemProxy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SystemProxy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SystemProxy", err)
		}
	}
	return nil
}
func (this *GetSystemIconReq) Validate() error {
	return nil
}
func (this *GetSystemIconReply) Validate() error {
	return nil
}

var _regex_UpdateSystemLanguageReq_Language = regexp.MustCompile(`EN|ZH`)

func (this *UpdateSystemLanguageReq) Validate() error {
	if !_regex_UpdateSystemLanguageReq_Language.MatchString(this.Language) {
		return github_com_mwitkow_go_proto_validators.FieldError("Language", fmt.Errorf(`value '%v' must be a string conforming to regex "EN|ZH"`, this.Language))
	}
	return nil
}
func (this *UpdateSystemLanguageReply) Validate() error {
	return nil
}
func (this *UpdateSystemCfgReq) Validate() error {
	return nil
}
func (this *UpdateSystemCfgReply) Validate() error {
	return nil
}
func (this *SystemProxyInfo) Validate() error {
	return nil
}
func (this *GetSystemProxyReq) Validate() error {
	return nil
}
func (this *GetSystemProxyReply) Validate() error {
	if this.SystemProxy != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.SystemProxy); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("SystemProxy", err)
		}
	}
	return nil
}

var _regex_UpdateSystemProxyReq_HttpProxy = regexp.MustCompile(`^http://[^\s]+|^(\s&&[^\f\n\r\t\v])*`)
var _regex_UpdateSystemProxyReq_HttpsProxy = regexp.MustCompile(`^https://[^\s]+|^(\s&&[^\f\n\r\t\v])*`)

func (this *UpdateSystemProxyReq) Validate() error {
	if !_regex_UpdateSystemProxyReq_HttpProxy.MatchString(this.HttpProxy) {
		return github_com_mwitkow_go_proto_validators.FieldError("HttpProxy", fmt.Errorf(`value '%v' must be a string conforming to regex "^http://[^\\s]+|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.HttpProxy))
	}
	if !_regex_UpdateSystemProxyReq_HttpsProxy.MatchString(this.HttpsProxy) {
		return github_com_mwitkow_go_proto_validators.FieldError("HttpsProxy", fmt.Errorf(`value '%v' must be a string conforming to regex "^https://[^\\s]+|^(\\s&&[^\\f\\n\\r\\t\\v])*"`, this.HttpsProxy))
	}
	return nil
}
func (this *UpdateSystemProxyReply) Validate() error {
	return nil
}

var _regex_GetSystemStatsReq_Type = regexp.MustCompile(`load|cpu|mem|net_rx|net_tx`)
var _regex_GetSystemStatsReq_Scope = regexp.MustCompile(`2h|24h`)

func (this *GetSystemStatsReq) Validate() error {
	if !_regex_GetSystemStatsReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "load|cpu|mem|net_rx|net_tx"`, this.Type))
	}
	if !_regex_GetSystemStatsReq_Scope.MatchString(this.Scope) {
		return github_com_mwitkow_go_proto_validators.FieldError("Scope", fmt.Errorf(`value '%v' must be a string conforming to regex "2h|24h"`, this.Scope))
	}
	return nil
}
func (this *StatsInfo) Validate() error {
	return nil
}
func (this *GetSystemStatsReply) Validate() error {
	for _, item := range this.Stats {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Stats", err)
			}
		}
	}
	return nil
}
func (this *SetSystemStatsCfgReq) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *SetSystemStatsCfgReply) Validate() error {
	return nil
}
func (this *ListAuditLogReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListAuditLogReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListAuditLogReply_Details) Validate() error {
	return nil
}

var _regex_ListSystemLogsReq_Level = regexp.MustCompile(`error|warn`)
var _regex_ListSystemLogsReq_Module = regexp.MustCompile(`apiserver|task_worker|task_server|scanner|engine`)

func (this *ListSystemLogsReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	for _, item := range this.Level {
		if !_regex_ListSystemLogsReq_Level.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Level", fmt.Errorf(`value '%v' must be a string conforming to regex "error|warn"`, item))
		}
	}
	for _, item := range this.Module {
		if !_regex_ListSystemLogsReq_Module.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Module", fmt.Errorf(`value '%v' must be a string conforming to regex "apiserver|task_worker|task_server|scanner|engine"`, item))
		}
	}
	return nil
}
func (this *ListSystemLogsReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListSystemLogsReply_Details) Validate() error {
	return nil
}
func (this *GetLicenseReq) Validate() error {
	return nil
}
func (this *GetLicenseReply) Validate() error {
	return nil
}
func (this *UpdateLicenseReq) Validate() error {
	return nil
}
func (this *UpdateLicenseReply) Validate() error {
	return nil
}

var _regex_NetworkDebugReq_Type = regexp.MustCompile(`ping|nslookup|traceroute|nc`)
var _regex_NetworkDebugReq_Target = regexp.MustCompile(`[a-zA-Z0-9][-a-zA-Z0-9]{0,62}(\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62})+\.?|((2(5[0-5]|[0-4]\d))|[0-1]?\d{1,2})(\.((2(5[0-5]|[0-4]\d))|[0-1]?\d{1,2})){3}`)

func (this *NetworkDebugReq) Validate() error {
	if !_regex_NetworkDebugReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "ping|nslookup|traceroute|nc"`, this.Type))
	}
	if !_regex_NetworkDebugReq_Target.MatchString(this.Target) {
		return github_com_mwitkow_go_proto_validators.FieldError("Target", fmt.Errorf(`value '%v' must be a string conforming to regex "[a-zA-Z0-9][-a-zA-Z0-9]{0,62}(\\.[a-zA-Z0-9][-a-zA-Z0-9]{0,62})+\\.?|((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})(\\.((2(5[0-5]|[0-4]\\d))|[0-1]?\\d{1,2})){3}"`, this.Target))
	}
	return nil
}
func (this *NetworkDebugReply) Validate() error {
	return nil
}

var _regex_ListNotifyConfReq_ModuleName = regexp.MustCompile(`all|alert|baseline|leak|system`)
var _regex_ListNotifyConfReq_NotifyType = regexp.MustCompile(`all|syslog|webhook|email`)
var _regex_ListNotifyConfReq_Enable = regexp.MustCompile(`all|enable|disable`)

func (this *ListNotifyConfReq) Validate() error {
	for _, item := range this.ModuleName {
		if !_regex_ListNotifyConfReq_ModuleName.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("ModuleName", fmt.Errorf(`value '%v' must be a string conforming to regex "all|alert|baseline|leak|system"`, item))
		}
	}
	for _, item := range this.NotifyType {
		if !_regex_ListNotifyConfReq_NotifyType.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("NotifyType", fmt.Errorf(`value '%v' must be a string conforming to regex "all|syslog|webhook|email"`, item))
		}
	}
	for _, item := range this.Enable {
		if !_regex_ListNotifyConfReq_Enable.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Enable", fmt.Errorf(`value '%v' must be a string conforming to regex "all|enable|disable"`, item))
		}
	}
	return nil
}
func (this *ListNotifyConfReply) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	return nil
}
func (this *ListNotifyConfReply_Details) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}

var _regex_UpdateNotifyConfReq_Enable = regexp.MustCompile(`enable|disable`)

func (this *UpdateNotifyConfReq) Validate() error {
	if this.Id == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must not be an empty string`, this.Id))
	}
	if !_regex_UpdateNotifyConfReq_Enable.MatchString(this.Enable) {
		return github_com_mwitkow_go_proto_validators.FieldError("Enable", fmt.Errorf(`value '%v' must be a string conforming to regex "enable|disable"`, this.Enable))
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *UpdateNotifyConfReply) Validate() error {
	return nil
}

var _regex_EnableNotifyConfReq_Enable = regexp.MustCompile(`enable|disable`)

func (this *EnableNotifyConfReq) Validate() error {
	if this.Id == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must not be an empty string`, this.Id))
	}
	if !_regex_EnableNotifyConfReq_Enable.MatchString(this.Enable) {
		return github_com_mwitkow_go_proto_validators.FieldError("Enable", fmt.Errorf(`value '%v' must be a string conforming to regex "enable|disable"`, this.Enable))
	}
	return nil
}
func (this *EnableNotifyConfReply) Validate() error {
	return nil
}

var _regex_TestNotifyConfReq_ModuleName = regexp.MustCompile(`alert|baseline|leak|system`)
var _regex_TestNotifyConfReq_NotifyType = regexp.MustCompile(`syslog|webhook|email`)

func (this *TestNotifyConfReq) Validate() error {
	if !_regex_TestNotifyConfReq_ModuleName.MatchString(this.ModuleName) {
		return github_com_mwitkow_go_proto_validators.FieldError("ModuleName", fmt.Errorf(`value '%v' must be a string conforming to regex "alert|baseline|leak|system"`, this.ModuleName))
	}
	if !_regex_TestNotifyConfReq_NotifyType.MatchString(this.NotifyType) {
		return github_com_mwitkow_go_proto_validators.FieldError("NotifyType", fmt.Errorf(`value '%v' must be a string conforming to regex "syslog|webhook|email"`, this.NotifyType))
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *TestNotifyConfReply) Validate() error {
	return nil
}

var _regex_ListExportTaskReq_Type = regexp.MustCompile(`all|alert_event|alert_activity|baseline|leak|weakpwd|system|audit`)
var _regex_ListExportTaskReq_Status = regexp.MustCompile(`all|padding|doing|finish|failed`)

func (this *ListExportTaskReq) Validate() error {
	for _, item := range this.Type {
		if !_regex_ListExportTaskReq_Type.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "all|alert_event|alert_activity|baseline|leak|weakpwd|system|audit"`, item))
		}
	}
	for _, item := range this.Status {
		if !_regex_ListExportTaskReq_Status.MatchString(item) {
			return github_com_mwitkow_go_proto_validators.FieldError("Status", fmt.Errorf(`value '%v' must be a string conforming to regex "all|padding|doing|finish|failed"`, item))
		}
	}
	return nil
}
func (this *ListExportTaskReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListExportTaskReply_Details) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *AddExportTaskReq) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *AddExportTaskReply) Validate() error {
	return nil
}
func (this *DeleteExportTaskReq) Validate() error {
	return nil
}
func (this *DeleteExportTaskReply) Validate() error {
	return nil
}
func (this *ListNotifyReq) Validate() error {
	return nil
}
func (this *ListNotifyReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListNotifyReply_Details) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *UpdateNotifyReq) Validate() error {
	return nil
}
func (this *UpdateNotifyReply) Validate() error {
	return nil
}
func (this *StatsNotifyReq) Validate() error {
	return nil
}
func (this *StatsNotifyReply) Validate() error {
	return nil
}

var _regex_ThreatTopsReq_Type = regexp.MustCompile(`activity|event`)

func (this *ThreatTopsReq) Validate() error {
	if !_regex_ThreatTopsReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "activity|event"`, this.Type))
	}
	return nil
}
func (this *ThreatTopsReply) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ThreatTopsReply_Details) Validate() error {
	return nil
}
func (this *ThreatTrendsReq) Validate() error {
	return nil
}
func (this *ThreatTrendsReply) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ThreatTrendsReply_Item) Validate() error {
	return nil
}
func (this *ListThreatReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	for _, item := range this.AdvancedSearch {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("AdvancedSearch", err)
			}
		}
	}
	return nil
}
func (this *ListThreatReq_Details) Validate() error {
	return nil
}
func (this *ListThreatReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListThreatReply_Details) Validate() error {
	if this.AttackFlow != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AttackFlow); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AttackFlow", err)
		}
	}
	return nil
}
func (this *GetThreatNamesReq) Validate() error {
	return nil
}
func (this *GetThreatNamesReply) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetThreatReq) Validate() error {
	return nil
}
func (this *GetThreatReply) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	if this.AttackFlow != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AttackFlow); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AttackFlow", err)
		}
	}
	for _, item := range this.Activities {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Activities", err)
			}
		}
	}
	return nil
}
func (this *ActionThreatReq) Validate() error {
	if !(this.EventStatus > -1) {
		return github_com_mwitkow_go_proto_validators.FieldError("EventStatus", fmt.Errorf(`value '%v' must be greater than '-1'`, this.EventStatus))
	}
	if !(this.EventStatus < 4) {
		return github_com_mwitkow_go_proto_validators.FieldError("EventStatus", fmt.Errorf(`value '%v' must be less than '4'`, this.EventStatus))
	}
	return nil
}
func (this *ActionThreatReply) Validate() error {
	return nil
}
func (this *ListActivityReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ActivityDetails) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ListActivityReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *GetActivityNamesReq) Validate() error {
	return nil
}
func (this *GetActivityNamesReply) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetActivityReq) Validate() error {
	return nil
}
func (this *GetActivityReply) Validate() error {
	if this.Details != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Details); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Details", err)
		}
	}
	return nil
}
func (this *ListSensitiveEntryReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListSensitiveEntryReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListSensitiveEntryReply_Details) Validate() error {
	return nil
}

var _regex_AddSensitiveEntryReq_Type = regexp.MustCompile(`user|group|computer|honeyuser`)

func (this *AddSensitiveEntryReq) Validate() error {
	if !_regex_AddSensitiveEntryReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "user|group|computer|honeyuser"`, this.Type))
	}
	return nil
}
func (this *AddSensitiveEntryReply) Validate() error {
	return nil
}

var _regex_ListDomainEntryReq_Type = regexp.MustCompile(`user|group|computer|honeyuser`)

func (this *ListDomainEntryReq) Validate() error {
	if !_regex_ListDomainEntryReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "user|group|computer|honeyuser"`, this.Type))
	}
	return nil
}
func (this *ListDomainEntryReply) Validate() error {
	return nil
}
func (this *DeleteSensitiveEntryReq) Validate() error {
	return nil
}
func (this *DeleteSensitiveEntryReply) Validate() error {
	return nil
}
func (this *ListThreatWhitelistReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListThreatWhitelistReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListThreatWhitelistReply_Details) Validate() error {
	for _, item := range this.Rules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Rules", err)
			}
		}
	}
	return nil
}
func (this *ListThreatWhitelistReply_DetailsRuleInfo) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetThreatWhitelistFieldReq) Validate() error {
	return nil
}
func (this *GetThreatWhitelistFieldReply) Validate() error {
	return nil
}
func (this *AddThreatWhitelistReq) Validate() error {
	for _, item := range this.Rules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Rules", err)
			}
		}
	}
	if !(this.Origin > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Origin", fmt.Errorf(`value '%v' must be greater than '0'`, this.Origin))
	}
	if !(this.Origin < 3) {
		return github_com_mwitkow_go_proto_validators.FieldError("Origin", fmt.Errorf(`value '%v' must be less than '3'`, this.Origin))
	}
	return nil
}
func (this *AddThreatWhitelistReqRuleInfo) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *AddThreatWhitelistReply) Validate() error {
	return nil
}
func (this *UpdateThreatWhitelistReq) Validate() error {
	for _, item := range this.Rules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Rules", err)
			}
		}
	}
	return nil
}
func (this *UpdateThreatWhitelistReqRuleInfo) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *UpdateThreatWhitelistReply) Validate() error {
	return nil
}
func (this *DeleteThreatWhitelistReq) Validate() error {
	return nil
}
func (this *DeleteThreatWhitelistReply) Validate() error {
	return nil
}
func (this *ListThreatBlockReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListThreatBlockReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListThreatBlockReply_Results) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ListThreatBlockReply_Details) Validate() error {
	for _, item := range this.Results {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Results", err)
			}
		}
	}
	return nil
}
func (this *AddThreatBlockReq) Validate() error {
	return nil
}
func (this *AddThreatBlockReply) Validate() error {
	return nil
}
func (this *UpdateThreatBlockReq) Validate() error {
	return nil
}
func (this *UpdateThreatBlockReply) Validate() error {
	return nil
}
func (this *DeleteThreatBlockReq) Validate() error {
	return nil
}
func (this *DeleteThreatBlockReply) Validate() error {
	return nil
}

var _regex_ScanRiskStatsReq_Type = regexp.MustCompile(`baseline|leak`)

func (this *ScanRiskStatsReq) Validate() error {
	if !_regex_ScanRiskStatsReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "baseline|leak"`, this.Type))
	}
	return nil
}
func (this *ScanRiskStatsReply) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ScanRiskStatsReply_Details) Validate() error {
	return nil
}
func (this *ListBaselineReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListBaselineReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListBaselineReply_Details) Validate() error {
	return nil
}
func (this *GetBaselineReq) Validate() error {
	return nil
}
func (this *GetBaselineReply) Validate() error {
	for _, item := range this.Entries {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Entries", err)
			}
		}
	}
	return nil
}
func (this *GetBaselineReplyEntryInfo) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *ListLeakReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListLeakReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListLeakReply_Details) Validate() error {
	return nil
}
func (this *ListWeakPwdReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListWeakPwdReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListWeakPwdReply_Details) Validate() error {
	return nil
}

var _regex_ListScanTaskReq_Cycle = regexp.MustCompile(`all|cycle|once`)
var _regex_ListScanTaskReq_Type = regexp.MustCompile(`all|baseline|leak|weakpwd`)
var _regex_ListScanTaskReq_Status = regexp.MustCompile(`all|PENDING|RUNNING|FINISH|FAILURE`)

func (this *ListScanTaskReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	if !_regex_ListScanTaskReq_Cycle.MatchString(this.Cycle) {
		return github_com_mwitkow_go_proto_validators.FieldError("Cycle", fmt.Errorf(`value '%v' must be a string conforming to regex "all|cycle|once"`, this.Cycle))
	}
	if !_regex_ListScanTaskReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "all|baseline|leak|weakpwd"`, this.Type))
	}
	if !_regex_ListScanTaskReq_Status.MatchString(this.Status) {
		return github_com_mwitkow_go_proto_validators.FieldError("Status", fmt.Errorf(`value '%v' must be a string conforming to regex "all|PENDING|RUNNING|FINISH|FAILURE"`, this.Status))
	}
	return nil
}
func (this *ListScanTaskReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListScanTaskReply_Details) Validate() error {
	return nil
}
func (this *GetScanTaskReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *GetScanTaskReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *GetScanTaskReply_Details) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}

var _regex_AddScanTaskReq_Type = regexp.MustCompile(`all|baseline|leak|weakpwd`)

func (this *AddScanTaskReq) Validate() error {
	if !_regex_AddScanTaskReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "all|baseline|leak|weakpwd"`, this.Type))
	}
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *AddScanTaskReply) Validate() error {
	return nil
}

var _regex_RecheckScanTaskReq_Type = regexp.MustCompile(`baseline|leak|weakpwd`)

func (this *RecheckScanTaskReq) Validate() error {
	if !_regex_RecheckScanTaskReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "baseline|leak|weakpwd"`, this.Type))
	}
	return nil
}
func (this *RecheckScanTaskReply) Validate() error {
	return nil
}
func (this *DeleteScanTaskReq) Validate() error {
	return nil
}
func (this *DeleteScanTaskReply) Validate() error {
	return nil
}
func (this *ListScanConfReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ListScanConfReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ScanConfDetail) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *SetScanConfReq) Validate() error {
	if !(this.CycleType > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("CycleType", fmt.Errorf(`value '%v' must be greater than '0'`, this.CycleType))
	}
	if !(this.CycleType < 4) {
		return github_com_mwitkow_go_proto_validators.FieldError("CycleType", fmt.Errorf(`value '%v' must be less than '4'`, this.CycleType))
	}
	return nil
}
func (this *SetScanConfReply) Validate() error {
	return nil
}
func (this *GetScanConfReq) Validate() error {
	return nil
}
func (this *GetScanConfReply) Validate() error {
	if this.Detail != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Detail); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Detail", err)
		}
	}
	return nil
}

var _regex_GetScanTmplNamesReq_Type = regexp.MustCompile(`all|baseline|leak|weakpwd`)

func (this *GetScanTmplNamesReq) Validate() error {
	if !_regex_GetScanTmplNamesReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "all|baseline|leak|weakpwd"`, this.Type))
	}
	return nil
}
func (this *GetScanTmplNamesReply) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *GetScanTmplNamesReplyTmplNames) Validate() error {
	return nil
}
func (this *UpdateScanConfReq) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *UpdateScanConfReply) Validate() error {
	return nil
}

var _regex_ListScanTmplReq_Type = regexp.MustCompile(`all|baseline|leak|weakpwd`)

func (this *ListScanTmplReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	if !_regex_ListScanTmplReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "all|baseline|leak|weakpwd"`, this.Type))
	}
	return nil
}
func (this *ListScanTmplReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *ListScanTmplReply_Details) Validate() error {
	return nil
}
func (this *GetScanTmplReq) Validate() error {
	return nil
}
func (this *PluginInfo) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetScanTmplReply) Validate() error {
	for _, item := range this.Plugins {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Plugins", err)
			}
		}
	}
	return nil
}
func (this *UpdateScanTmplReq) Validate() error {
	for _, item := range this.Plugins {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Plugins", err)
			}
		}
	}
	return nil
}
func (this *UpdateScanTmplReply) Validate() error {
	return nil
}
func (this *DeleteScanTmplReq) Validate() error {
	return nil
}
func (this *DeleteScanTmplReply) Validate() error {
	return nil
}
func (this *PluginInfoV2) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *AddScanTmplReq) Validate() error {
	for _, item := range this.Plugins {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Plugins", err)
			}
		}
	}
	return nil
}
func (this *AddScanTmplReply) Validate() error {
	return nil
}

var _regex_ListScanPluginReq_Type = regexp.MustCompile(`baseline|leak|weakpwd`)

func (this *ListScanPluginReq) Validate() error {
	if !_regex_ListScanPluginReq_Type.MatchString(this.Type) {
		return github_com_mwitkow_go_proto_validators.FieldError("Type", fmt.Errorf(`value '%v' must be a string conforming to regex "baseline|leak|weakpwd"`, this.Type))
	}
	return nil
}
func (this *ListScanPluginReply) Validate() error {
	for _, item := range this.Plugins {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Plugins", err)
			}
		}
	}
	return nil
}
func (this *DashboardStatsReq) Validate() error {
	return nil
}
func (this *DashboardStatsReply) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *DashboardTrendsReq) Validate() error {
	return nil
}
func (this *DashboardTrendsReply) Validate() error {
	return nil
}
func (this *DashboardLogStatsReq) Validate() error {
	return nil
}
func (this *DashboardLogStatsReply) Validate() error {
	for _, item := range this.List {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("List", err)
			}
		}
	}
	return nil
}
func (this *DashboardLogStatsReplyLogStatsList) Validate() error {
	return nil
}
func (this *ListAlertRuleReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *AttackFlowReply) Validate() error {
	for _, item := range this.Fields {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Fields", err)
			}
		}
	}
	return nil
}
func (this *AttackFlowReply_Field) Validate() error {
	return nil
}
func (this *AlertRuleInfo) Validate() error {
	if this.AttackFlow != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AttackFlow); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AttackFlow", err)
		}
	}
	return nil
}
func (this *ListAlertRuleReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.Rules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Rules", err)
			}
		}
	}
	return nil
}

var _regex_AlertDetection_EventType = regexp.MustCompile(`count|multi_eve|multi_pkt|multi_eve_pkt`)

func (this *AlertDetection) Validate() error {
	if !_regex_AlertDetection_EventType.MatchString(this.EventType) {
		return github_com_mwitkow_go_proto_validators.FieldError("EventType", fmt.Errorf(`value '%v' must be a string conforming to regex "count|multi_eve|multi_pkt|multi_eve_pkt"`, this.EventType))
	}
	return nil
}
func (this *AddAlertRuleReq) Validate() error {
	if this.Title == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must not be an empty string`, this.Title))
	}
	if !(this.Level > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Level", fmt.Errorf(`value '%v' must be greater than '0'`, this.Level))
	}
	if !(this.Level < 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("Level", fmt.Errorf(`value '%v' must be less than '6'`, this.Level))
	}
	if this.Detection != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Detection); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Detection", err)
		}
	}
	if this.AttackFlow != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AttackFlow); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AttackFlow", err)
		}
	}
	return nil
}
func (this *AddAlertRuleReply) Validate() error {
	return nil
}
func (this *UpdateAlertRuleReq) Validate() error {
	if this.ID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must not be an empty string`, this.ID))
	}
	if this.Detection != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Detection); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Detection", err)
		}
	}
	if this.AttackFlow != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AttackFlow); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AttackFlow", err)
		}
	}
	return nil
}
func (this *UpdateAlertRuleReply) Validate() error {
	return nil
}
func (this *DeleteAlertRuleReq) Validate() error {
	if this.ID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must not be an empty string`, this.ID))
	}
	return nil
}
func (this *DeleteAlertRuleReply) Validate() error {
	return nil
}
func (this *GetAlertTypesReq) Validate() error {
	return nil
}
func (this *GetAlertTypesReply) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetAlertRuleNamesReq) Validate() error {
	return nil
}
func (this *GetAlertRuleNamesReply) Validate() error {
	// Validation of proto3 map<> fields is unsupported.
	return nil
}
func (this *GetAlertRuleTagsReq) Validate() error {
	return nil
}
func (this *GetAlertRuleTagsReply) Validate() error {
	return nil
}
func (this *GetActivityRuleFieldsReq) Validate() error {
	return nil
}
func (this *GetActivityRuleFieldsReply) Validate() error {
	return nil
}
func (this *RuleNameItem) Validate() error {
	return nil
}
func (this *GetActivityRuleNamesReq) Validate() error {
	return nil
}
func (this *GetActivityRuleNamesReply) Validate() error {
	for _, item := range this.Rules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Rules", err)
			}
		}
	}
	return nil
}
func (this *GetActivityRuleUniqueFieldsReq) Validate() error {
	return nil
}
func (this *GetActivityRuleUniqueFieldsReply) Validate() error {
	return nil
}
func (this *ListActivityRuleReq) Validate() error {
	if !(this.PageIdx > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("PageIdx", fmt.Errorf(`value '%v' must be greater than '0'`, this.PageIdx))
	}
	return nil
}
func (this *ActivityRuleInfo) Validate() error {
	return nil
}
func (this *ListActivityRuleReply) Validate() error {
	if this.Page != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Page); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Page", err)
		}
	}
	for _, item := range this.Rules {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Rules", err)
			}
		}
	}
	return nil
}
func (this *GetActivityRuleReq) Validate() error {
	if this.ID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must not be an empty string`, this.ID))
	}
	return nil
}
func (this *GetActivityRuleReply) Validate() error {
	return nil
}
func (this *AddActivityRuleReq) Validate() error {
	if this.ID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must not be an empty string`, this.ID))
	}
	if this.Title == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must not be an empty string`, this.Title))
	}
	if !(this.Level > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Level", fmt.Errorf(`value '%v' must be greater than '0'`, this.Level))
	}
	if !(this.Level < 6) {
		return github_com_mwitkow_go_proto_validators.FieldError("Level", fmt.Errorf(`value '%v' must be less than '6'`, this.Level))
	}
	if this.Detection == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Detection", fmt.Errorf(`value '%v' must not be an empty string`, this.Detection))
	}
	return nil
}
func (this *AddActivityRuleReply) Validate() error {
	return nil
}
func (this *UpdateActivityRuleReq) Validate() error {
	if this.ID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must not be an empty string`, this.ID))
	}
	return nil
}
func (this *UpdateActivityRuleReply) Validate() error {
	return nil
}
func (this *DeleteActivityRuleReq) Validate() error {
	if this.ID == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("ID", fmt.Errorf(`value '%v' must not be an empty string`, this.ID))
	}
	return nil
}
func (this *DeleteActivityRuleReply) Validate() error {
	return nil
}
